server:
  port: 9001

spring:
  application:
    name: nacos-discovery-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848
        server-addr: 192.168.253.130:8848


management:
  endpoints:
    web:
      exposure:
        include: "*"