#server:
#  port: 8004
#
#spring:
#  application:
#      name: cloud-provider-payment
#  cloud:
#    zookeeper:
#        connect-string: 192.168.136.140:2181
server:
  port: 8004
spring:
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      connect-string: 106.15.203.32:2181
